// 세계의 명언 데이터베이스 (World Quotes Database)
// 총 115개의 엄선된 동서고금 세계 명언

const QUOTES_DATA = [
  // 1. 인생과 삶 (Life)
  {
    id: 1,
    quote_ko: "인생은 속도가 아니라 방향이다.",
    quote_en: "Life is a matter of direction, not speed.",
    author_ko: "요한 볼프강 폰 괴테",
    author_en: "Johann Wolfgang von Goethe",
    author_title: "독일의 문학가이자 철학자",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["방향", "속도", "삶의목표"]
  },
  {
    id: 2,
    quote_ko: "반성하지 않는 삶은 살 가치가 없다.",
    quote_en: "The unexamined life is not worth living.",
    author_ko: "소크라테스",
    author_en: "Socrates",
    author_title: "고대 그리스 철학자",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["성찰", "철학", "진리"]
  },
  {
    id: 3,
    quote_ko: "우리가 살고 있는 삶은 우리가 생각하는 대로 만들어진다.",
    quote_en: "Our life is what our thoughts make it.",
    author_ko: "마르쿠스 아우렐리우스",
    author_en: "Marcus Aurelius",
    author_title: "로마 제국의 16대 황제이자 스토아 철학자",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["생각", "마음가짐", "스토아"]
  },
  {
    id: 4,
    quote_ko: "삶이 있는 한 희망은 있다.",
    quote_en: "While there's life, there's hope.",
    author_ko: "마르쿠스 툴리우스 키케로",
    author_en: "Marcus Tullius Cicero",
    author_title: "고대 로마의 정치가이자 철학자",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["희망", "삶", "긍정"]
  },
  {
    id: 5,
    quote_ko: "인생에서 가장 큰 영광은 결코 넘어지지 않는 데 있는 것이 아니라, 넘어질 때마다 다시 일어서는 데 있다.",
    quote_en: "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    author_ko: "넬슨 만델라",
    author_en: "Nelson Mandela",
    author_title: "남아프리카 공화국 최초의 흑인 대통령",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["재기", "불굴", "영광"]
  },
  {
    id: 6,
    quote_ko: "시간은 인간이 쓸 수 있는 가장 값진 자본이다.",
    quote_en: "Time is the most valuable thing a man can spend.",
    author_ko: "테오프라스트스",
    author_en: "Theophrastus",
    author_title: "고대 그리스의 철학자",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["시간", "자산", "가치"]
  },
  {
    id: 7,
    quote_ko: "우리는 우리가 반복적으로 하는 행동의 결과물이다. 따라서 탁월함은 행동이 아니라 습관이다.",
    quote_en: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    author_ko: "윌 듀런트 (아리스토텔레스 철학 해석)",
    author_en: "Will Durant (on Aristotle)",
    author_title: "미국의 철학자이자 역사가",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["습관", "탁월함", "실천"]
  },
  {
    id: 8,
    quote_ko: "단순함이 궁극의 정교함이다.",
    quote_en: "Simplicity is the ultimate sophistication.",
    author_ko: "레오나르도 다빈치",
    author_en: "Leonardo da Vinci",
    author_title: "르네상스 시대의 천재 예술가이자 과학자",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["단순함", "정교함", "예술"]
  },
  {
    id: 9,
    quote_ko: "인생은 자전거를 타는 것과 같다. 균형을 유지하려면 계속 움직여야 한다.",
    quote_en: "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    author_ko: "알베르트 아인슈타인",
    author_en: "Albert Einstein",
    author_title: "이론물리학자, 노벨 물리학상 수상자",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["균형", "전진", "유지"]
  },
  {
    id: 10,
    quote_ko: "과거를 기억하지 못하는 자들은 그 과거를 반복하기 마련이다.",
    quote_en: "Those who cannot remember the past are condemned to repeat it.",
    author_ko: "조지 산타야나",
    author_en: "George Santayana",
    author_title: "스페인 출신의 철학자이자 시인",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["역사", "성찰", "배움"]
  },
  {
    id: 11,
    quote_ko: "인생의 목적은 이기는 것이 아니라 성장하고 나누는 것이다.",
    quote_en: "The purpose of life is not to win. The purpose of life is to grow and to share.",
    author_ko: "해럴드 쿠슈너",
    author_en: "Harold Kushner",
    author_title: "미국의 랍비이자 작가",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["성장", "나눔", "인생의의미"]
  },
  {
    id: 12,
    quote_ko: "우리가 삶을 바라보는 방식이 결국 우리의 삶이 된다.",
    quote_en: "The way we see life becomes our life.",
    author_ko: "존 러스킨",
    author_en: "John Ruskin",
    author_title: "영국의 비평가이자 사회사상가",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["관점", "시선", "태도"]
  },
  {
    id: 13,
    quote_ko: "인생은 스스로 만들어가는 예술 작품이다.",
    quote_en: "Life is a work of art created by oneself.",
    author_ko: "로맹 롤랑",
    author_en: "Romain Rolland",
    author_title: "프랑스의 소설가이자 노벨 문학상 수상자",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["창조", "예술", "자기주도"]
  },
  {
    id: 14,
    quote_ko: "어제는 역사이고, 내일은 수수께끼이며, 오늘은 선물이다. 그래서 우리는 그것을 '현재(Present)'라고 부른다.",
    quote_en: "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.",
    author_ko: "빌 킨",
    author_en: "Bil Keane",
    author_title: "미국의 만화가",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["현재", "선물", "오늘"]
  },
  {
    id: 15,
    quote_ko: "남의 뜻대로 움직이지 말고, 그대만의 별자리를 향해 걸어가라.",
    quote_en: "Follow your own star and do not be swayed by others.",
    author_ko: "단테 알리기에리",
    author_en: "Dante Alighieri",
    author_title: "이탈리아의 위대한 시인, 신곡의 저자",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["주관", "별", "길"]
  },
  {
    id: 16,
    quote_ko: "삶은 짧고 예술은 길며, 기회는 순식간에 지나가고 경험은 믿기 어렵다.",
    quote_en: "Life is short, the art long, opportunity fleeting, experience misleading.",
    author_ko: "히포크라테스",
    author_en: "Hippocrates",
    author_title: "의학의 아버지",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["시간의소중함", "학문", "기회"]
  },
  {
    id: 17,
    quote_ko: "남을 알고 자신을 알면 백 번 싸워도 위태롭지 않다.",
    quote_en: "If you know the enemy and know yourself, you need not fear the result of a hundred battles.",
    author_ko: "손자",
    author_en: "Sun Tzu",
    author_title: "고대 중국 춘추시대의 군사가이자 손자병법의 저자",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["지피지기", "지혜", "준비"]
  },
  {
    id: 18,
    quote_ko: "진정한 인간성은 어려운 상황에서 어떤 태도를 취하느냐에 달려 있다.",
    quote_en: "The ultimate measure of a man is not where he stands in moments of comfort, but where he stands at times of challenge.",
    author_ko: "마틴 루터 킹 주니어",
    author_en: "Martin Luther King Jr.",
    author_title: "미국의 인권 운동가이자 목사",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["태도", "시련", "품격"]
  },

  // 2. 성공과 도전 (Success & Challenge)
  {
    id: 19,
    quote_ko: "위대한 일을 하는 유일한 방법은 당신이 하는 일을 사랑하는 것이다.",
    quote_en: "The only way to do great work is to love what you do.",
    author_ko: "스티브 잡스",
    author_en: "Steve Jobs",
    author_title: "애플 창업자이자 혁신가",
    category: "success",
    category_ko: "성공과 도전",
    tags: ["열정", "성공", "직업"]
  },
  {
    id: 20,
    quote_ko: "나는 실패한 적이 없다. 단지 작동하지 않는 10,000가지 방법을 발견했을 뿐이다.",
    quote_en: "I have not failed. I've just found 10,000 ways that won't work.",
    author_ko: "토머스 에디슨",
    author_en: "Thomas A. Edison",
    author_title: "미국의 발명가이자 사업가",
    category: "success",
    category_ko: "성공과 도전",
    tags: ["도전", "끈기", "발견"]
  },
  {
    id: 21,
    quote_ko: "성공이란 열정을 잃지 않고 실패를 거듭해 나가는 능력이다.",
    quote_en: "Success is walking from failure to failure with no loss of enthusiasm.",
    author_ko: "윈스턴 처칠",
    author_en: "Winston Churchill",
    author_title: "제2차 세계대전을 승리로 이끈 영국의 수상",
    category: "success",
    category_ko: "성공과 도전",
    tags: ["열정", "실패", "극복"]
  },
  {
    id: 22,
    quote_ko: "꿈을 이룰 수 있는 가장 좋은 방법은 잠에서 깨어나는 것이다.",
    quote_en: "The best way to make your dreams come true is to wake up.",
    author_ko: "폴 발레리",
    author_en: "Paul Valéry",
    author_title: "프랑스의 시인이자 사상가",
    category: "success",
    category_ko: "성공과 도전",
    tags: ["행동", "꿈", "각성"]
  },
  {
    id: 23,
    quote_ko: "꿈꿀 수 있다면, 그것을 실행할 수도 있다.",
    quote_en: "If you can dream it, you can do it.",
    author_ko: "월트 디즈니",
    author_en: "Walt Disney",
    author_title: "디즈니 애니메이션의 창립자",
    category: "success",
    category_ko: "성공과 도전",
    tags: ["상상력", "실행", "꿈"]
  },
  {
    id: 24,
    quote_ko: "시작하는 방법은 말하는 것을 멈추고 행동하기 시작하는 것이다.",
    quote_en: "The way to get started is to quit talking and begin doing.",
    author_ko: "월트 디즈니",
    author_en: "Walt Disney",
    author_title: "디즈니 애니메이션의 창립자",
    category: "success",
    category_ko: "성공과 도전",
    tags: ["행동", "시작", "실천"]
  },
  {
    id: 25,
    quote_ko: "위험을 감수하지 않는 것이야말로 인생에서 가장 위험한 일이다.",
    quote_en: "The biggest risk is not taking any risk.",
    author_ko: "마크 저커버그",
    author_en: "Mark Zuckerberg",
    author_title: "메타(페이스북) 창업자",
    category: "success",
    category_ko: "성공과 도전",
    tags: ["모험", "도전", "위험"]
  },
  {
    id: 26,
    quote_ko: "당신이 할 수 있다고 믿든, 할 수 없다고 믿든, 당신이 옳다.",
    quote_en: "Whether you think you can, or you think you can't – you're right.",
    author_ko: "헨리 포드",
    author_en: "Henry Ford",
    author_title: "포드 모터 컴퍼니의 창업자",
    category: "success",
    category_ko: "성공과 도전",
    tags: ["신념", "마인드셋", "가능성"]
  },
  {
    id: 27,
    quote_ko: "기회는 일어나는 것이 아니라 당신이 만들어내는 것이다.",
    quote_en: "Opportunities don't happen. You create them.",
    author_ko: "크리스 그로서",
    author_en: "Chris Grosser",
    author_title: "기업가이자 작가",
    category: "success",
    category_ko: "성공과 도전",
    tags: ["기회", "창조", "주도성"]
  },
  {
    id: 28,
    quote_ko: "성공의 비결은 결코 포기하지 않는 끈기에 있다.",
    quote_en: "The secret of success is constancy to purpose.",
    author_ko: "벤저민 디즈레일리",
    author_en: "Benjamin Disraeli",
    author_title: "영국의 정치가이자 총리",
    category: "success",
    category_ko: "성공과 도전",
    tags: ["끈기", "일관성", "목표"]
  },
  {
    id: 29,
    quote_ko: "1%의 영감과 99%의 땀이 천재를 만든다.",
    quote_en: "Genius is one percent inspiration, ninety-nine percent perspiration.",
    author_ko: "토머스 에디슨",
    author_en: "Thomas A. Edison",
    author_title: "미국의 발명가",
    category: "success",
    category_ko: "성공과 도전",
    tags: ["노력", "땀", "천재"]
  },
  {
    id: 30,
    quote_ko: "승리는 가장 끈기 있는 자에게 돌아간다.",
    quote_en: "Victory belongs to the most persevering.",
    author_ko: "나폴레옹 보나파르트",
    author_en: "Napoleon Bonaparte",
    author_title: "프랑스의 군인이자 황제",
    category: "success",
    category_ko: "성공과 도전",
    tags: ["승리", "인내", "결의"]
  },
  {
    id: 31,
    quote_ko: "천 리 길도 한 걸음부터 시작된다.",
    quote_en: "A journey of a thousand miles begins with a single step.",
    author_ko: "노자",
    author_en: "Lao Tzu",
    author_title: "고대 중국의 철학자, 도가의 시조",
    category: "success",
    category_ko: "성공과 도전",
    tags: ["첫걸음", "시작", "도약"]
  },
  {
    id: 32,
    quote_ko: "지금 자면 꿈을 꾸지만, 지금 노력하면 꿈을 이룬다.",
    quote_en: "If you sleep now, you will dream; if you study now, you will live your dream.",
    author_ko: "하버드 대학 도서관 명언",
    author_en: "Harvard Library Proverb",
    author_title: "세계적인 학문의 전당 격언",
    category: "success",
    category_ko: "성공과 도전",
    tags: ["노력", "공부", "실현"]
  },
  {
    id: 33,
    quote_ko: "행동 없는 비전은 백일몽이고, 비전 없는 행동은 악몽이다.",
    quote_en: "Vision without action is a daydream. Action without vision is a nightmare.",
    author_ko: "일본 속담",
    author_en: "Japanese Proverb",
    author_title: "동양의 격언",
    category: "success",
    category_ko: "성공과 도전",
    tags: ["비전", "실행", "균형"]
  },
  {
    id: 34,
    quote_ko: "완벽함이란 더 이상 보탤 것이 없을 때가 아니라, 더 이상 뺄 것이 없을 때 완성된다.",
    quote_en: "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.",
    author_ko: "앙투안 드 생텍쥐페리",
    author_en: "Antoine de Saint-Exupéry",
    author_title: "프랑스의 작가이자 비행사, 어린 왕자의 저자",
    category: "success",
    category_ko: "성공과 도전",
    tags: ["완벽", "단순화", "본질"]
  },
  {
    id: 35,
    quote_ko: "계획 없는 목표는 단지 소망에 불과하다.",
    quote_en: "A goal without a plan is just a wish.",
    author_ko: "앙투안 드 생텍쥐페리",
    author_en: "Antoine de Saint-Exupéry",
    author_title: "프랑스의 작가, 어린 왕자의 저자",
    category: "success",
    category_ko: "성공과 도전",
    tags: ["계획", "목표", "구체화"]
  },
  {
    id: 36,
    quote_ko: "오늘 할 수 있는 일을 내일로 미루지 마라.",
    quote_en: "Never leave that till tomorrow which you can do today.",
    author_ko: "벤저민 프랭클린",
    author_en: "Benjamin Franklin",
    author_title: "미국의 건국 아버지이자 과학자",
    category: "success",
    category_ko: "성공과 도전",
    tags: ["시간관리", "실행력", "부지런함"]
  },

  // 3. 지혜와 배움 (Wisdom & Learning)
  {
    id: 37,
    quote_ko: "지혜의 시작은 무지를 인정하는 데 있다.",
    quote_en: "The only true wisdom is in knowing you know nothing.",
    author_ko: "소크라테스",
    author_en: "Socrates",
    author_title: "고대 그리스 철학자",
    category: "wisdom",
    category_ko: "지혜와 배움",
    tags: ["겸손", "지혜", "무지"]
  },
  {
    id: 38,
    quote_ko: "상상력은 지식보다 중요하다. 지식은 유한하지만 상상력은 온 세상을 감싸 안는다.",
    quote_en: "Imagination is more important than knowledge. For knowledge is limited, whereas imagination embraces the entire world.",
    author_ko: "알베르트 아인슈타인",
    author_en: "Albert Einstein",
    author_title: "이론물리학자, 상대성 이론 창시자",
    category: "wisdom",
    category_ko: "지혜와 배움",
    tags: ["상상력", "창의성", "지식"]
  },
  {
    id: 39,
    quote_ko: "배우고 때로 익히면 또한 기쁘지 아니한가.",
    quote_en: "Is it not pleasant to learn with a constant perseverance and application?",
    author_ko: "공자",
    author_en: "Confucius",
    author_title: "고대 중국 유학의 시조, 논어의 주인공",
    category: "wisdom",
    category_ko: "지혜와 배움",
    tags: ["배움", "기쁨", "익힘"]
  },
  {
    id: 40,
    quote_ko: "교육의 뿌리는 쓰지만 그 열매는 달다.",
    quote_en: "The roots of education are bitter, but the fruit is sweet.",
    author_ko: "아리스토텔레스",
    author_en: "Aristotle",
    author_title: "고대 그리스의 철학자이자 박식가",
    category: "wisdom",
    category_ko: "지혜와 배움",
    tags: ["교육", "인내", "결실"]
  },
  {
    id: 41,
    quote_ko: "책을 읽지 않는 사람은 글을 읽지 못하는 사람보다 나을 것이 없다.",
    quote_en: "A person who won't read has no advantage over one who can't read.",
    author_ko: "마크 트웨인",
    author_en: "Mark Twain",
    author_title: "미국의 대표적 소설가이자 유머리스트",
    category: "wisdom",
    category_ko: "지혜와 배움",
    tags: ["독서", "책", "통찰"]
  },
  {
    id: 42,
    quote_ko: "아는 것을 안다고 하고 모르는 것을 모른다고 하는 것, 이것이 곧 아는 것이다.",
    quote_en: "To know what you know and what you do not know, that is true knowledge.",
    author_ko: "공자",
    author_en: "Confucius",
    author_title: "고대 중국 유학의 시조",
    category: "wisdom",
    category_ko: "지혜와 배움",
    tags: ["메타인지", "솔직함", "진정한지식"]
  },
  {
    id: 43,
    quote_ko: "생각하지 않고 배우면 어둡고, 배우지 않고 생각하면 위태롭다.",
    quote_en: "Learning without thought is labor lost; thought without learning is perilous.",
    author_ko: "공자",
    author_en: "Confucius",
    author_title: "고대 중국 유학의 시조",
    category: "wisdom",
    category_ko: "지혜와 배움",
    tags: ["사유", "학습", "조화"]
  },
  {
    id: 44,
    quote_ko: "지식에 투자하는 것이 가장 높은 이자를 지급한다.",
    quote_en: "An investment in knowledge pays the best interest.",
    author_ko: "벤저민 프랭클린",
    author_en: "Benjamin Franklin",
    author_title: "미국의 정치가이자 발명가",
    category: "wisdom",
    category_ko: "지혜와 배움",
    tags: ["투자", "배움", "가치"]
  },
  {
    id: 45,
    quote_ko: "어리석은 자는 멀리서 행복을 찾고, 현명한 자는 발밑에서 행복을 키운다.",
    quote_en: "The foolish man seeks happiness in the distance, the wise grows it under his feet.",
    author_ko: "제임스 오펜하임",
    author_en: "James Oppenheim",
    author_title: "미국의 시인이자 소설가",
    category: "wisdom",
    category_ko: "지혜와 배움",
    tags: ["현명함", "행복", "일상"]
  },
  {
    id: 46,
    quote_ko: "질문하지 않는 자는 배울 수 없다.",
    quote_en: "He who asks is a fool for five minutes, but he who does not ask remains a fool forever.",
    author_ko: "중국 격언",
    author_en: "Chinese Proverb",
    author_title: "고대 동양의 지혜",
    category: "wisdom",
    category_ko: "지혜와 배움",
    tags: ["질문", "호기심", "배움"]
  },
  {
    id: 47,
    quote_ko: "마음을 열지 않는 공부는 바다에 물 한 방울 떨구는 것과 같다.",
    quote_en: "The mind is not a vessel to be filled, but a fire to be kindled.",
    author_ko: "플루타르코스",
    author_en: "Plutarch",
    author_title: "고대 그리스의 전기 작가이자 도덕주의자",
    category: "wisdom",
    category_ko: "지혜와 배움",
    tags: ["점화", "영감", "마음"]
  },
  {
    id: 48,
    quote_ko: "침묵은 종종 가장 웅변적인 대화이다.",
    quote_en: "Silence is one of the great arts of conversation.",
    author_ko: "마르쿠스 툴리우스 키케로",
    author_en: "Marcus Tullius Cicero",
    author_title: "로마의 철학자이자 웅변가",
    category: "wisdom",
    category_ko: "지혜와 배움",
    tags: ["침묵", "경청", "대화"]
  },
  {
    id: 49,
    quote_ko: "현명한 사람은 남의 잘못에서 자신의 허물을 고친다.",
    quote_en: "A wise man learns from the mistakes of others.",
    author_ko: "푸블릴리우스 시루스",
    author_en: "Publilius Syrus",
    author_title: "고대 로마의 작가이자 격언가",
    category: "wisdom",
    category_ko: "지혜와 배움",
    tags: ["타산지석", "겸허", "성장"]
  },
  {
    id: 50,
    quote_ko: "자신을 이기는 자가 가장 강한 사람이다.",
    quote_en: "He who conquers himself is the mightiest warrior.",
    author_ko: "공자",
    author_en: "Confucius",
    author_title: "고대 중국의 사상가",
    category: "wisdom",
    category_ko: "지혜와 배움",
    tags: ["극기", "자제력", "진정한강함"]
  },
  {
    id: 51,
    quote_ko: "가장 깊은 강은 가장 고요하게 흐른다.",
    quote_en: "Still waters run deep.",
    author_ko: "서양 격언",
    author_en: "Western Proverb",
    author_title: "전통 서양 지혜",
    category: "wisdom",
    category_ko: "지혜와 배움",
    tags: ["겸손", "깊이", "고요"]
  },
  {
    id: 52,
    quote_ko: "물고기를 한 마리 주면 하루를 먹고살 수 있지만, 물고기 잡는 법을 가르쳐 주면 평생을 먹고살 수 있다.",
    quote_en: "Give a man a fish and you feed him for a day; teach a man to fish and you feed him for a lifetime.",
    author_ko: "마이모니데스",
    author_en: "Maimonides",
    author_title: "중세 유대인 철학자이자 의사",
    category: "wisdom",
    category_ko: "지혜와 배움",
    tags: ["자립", "교육", "지혜"]
  },
  {
    id: 53,
    quote_ko: "화는 남에게 던지기 위해 뜨거운 숯을 손에 쥐는 것과 같다. 결국 화상을 입는 것은 자기 자신이다.",
    quote_en: "Holding onto anger is like drinking poison and expecting the other person to die.",
    author_ko: "붓다 (석가모니)",
    author_en: "Buddha",
    author_title: "불교의 창시자이자 깨달은 자",
    category: "wisdom",
    category_ko: "지혜와 배움",
    tags: ["분노", "평온", "자기관리"]
  },
  {
    id: 54,
    quote_ko: "자연을 깊이 관찰하라. 그러면 모든 것을 더 잘 이해하게 될 것이다.",
    quote_en: "Look deep into nature, and then you will understand everything better.",
    author_ko: "알베르트 아인슈타인",
    author_en: "Albert Einstein",
    author_title: "이론물리학자",
    category: "wisdom",
    category_ko: "지혜와 배움",
    tags: ["자연", "통찰", "이해"]
  },

  // 4. 용기와 희망 (Courage & Hope)
  {
    id: 55,
    quote_ko: "희망은 어둠 속에서 시작된다. 일어나서 옳은 일을 하려 할 때 새벽이 온다.",
    quote_en: "Hope begins in the dark, the stubborn hope that if you just show up and try to do the right thing, the dawn will come.",
    author_ko: "앤 라모트",
    author_en: "Anne Lamott",
    author_title: "미국의 소설가이자 에세이스트",
    category: "courage",
    category_ko: "용기와 희망",
    tags: ["희망", "새벽", "용기"]
  },
  {
    id: 56,
    quote_ko: "용기란 두려움이 없는 것이 아니라, 두려움보다 더 중요한 것이 있음을 아는 것이다.",
    quote_en: "Courage is not the absence of fear, but rather the judgment that something else is more important than fear.",
    author_ko: "앰브로즈 레드문",
    author_en: "Ambrose Redmoon",
    author_title: "미국의 작가이자 록 음악 매니저",
    category: "courage",
    category_ko: "용기와 희망",
    tags: ["용기", "두려움극복", "가치"]
  },
  {
    id: 57,
    quote_ko: "비바람이 지나간 뒤에야 비로소 무지개가 뜬다.",
    quote_en: "The greater the storm, the brighter the rainbow.",
    author_ko: "서양 속담",
    author_en: "Western Proverb",
    author_title: "희망의 격언",
    category: "courage",
    category_ko: "용기와 희망",
    tags: ["시련", "무지개", "희망"]
  },
  {
    id: 58,
    quote_ko: "세상은 고통으로 가득하지만, 한편 그것을 이겨내는 일로도 가득 차 있다.",
    quote_en: "Although the world is full of suffering, it is full also of the overcoming of it.",
    author_ko: "헬렌 켈러",
    author_en: "Helen Keller",
    author_title: "장애를 극복한 미국의 작가이자 교육가",
    category: "courage",
    category_ko: "용기와 희망",
    tags: ["극복", "고통", "승리"]
  },
  {
    id: 59,
    quote_ko: "어둠을 탓하기보다는 한 자루의 촛불을 켜라.",
    quote_en: "It is better to light a candle than curse the darkness.",
    author_ko: "엘리너 루스벨트",
    author_en: "Eleanor Roosevelt",
    author_title: "미국의 퍼스트레이디이자 인권운동가",
    category: "courage",
    category_ko: "용기와 희망",
    tags: ["촛불", "실천", "희망"]
  },
  {
    id: 60,
    quote_ko: "우리가 두려워해야 할 유일한 것은 두려움 그 자체다.",
    quote_en: "The only thing we have to fear is fear itself.",
    author_ko: "프랭클린 D. 루스벨트",
    author_en: "Franklin D. Roosevelt",
    author_title: "미국의 제32대 대통령",
    category: "courage",
    category_ko: "용기와 희망",
    tags: ["두려움", "결단", "용기"]
  },
  {
    id: 61,
    quote_ko: "나를 죽이지 못하는 고통은 나를 더욱 강하게 만들 뿐이다.",
    quote_en: "That which does not kill us makes us stronger.",
    author_ko: "프리드리히 니체",
    author_en: "Friedrich Nietzsche",
    author_title: "독일의 실존주의 철학자",
    category: "courage",
    category_ko: "용기와 희망",
    tags: ["시련", "강인함", "성장"]
  },
  {
    id: 62,
    quote_ko: "바람이 불지 않을 때 바람개비를 돌리는 방법은 앞으로 달려가는 것이다.",
    quote_en: "When the wind does not blow, the only way to turn the windmill is to run forward.",
    author_ko: "데일 카네기",
    author_en: "Dale Carnegie",
    author_title: "미국의 자기계발 전문가이자 작가",
    category: "courage",
    category_ko: "용기와 희망",
    tags: ["적극성", "도전", "돌파"]
  },
  {
    id: 63,
    quote_ko: "겨울이 오면 봄 또한 멀지 않으리.",
    quote_en: "If Winter comes, can Spring be far behind?",
    author_ko: "퍼시 비시 셸리",
    author_en: "Percy Bysshe Shelley",
    author_title: "영국의 낭만파 시인",
    category: "courage",
    category_ko: "용기와 희망",
    tags: ["봄", "기다림", "희망"]
  },
  {
    id: 64,
    quote_ko: "안전한 항구에 정박해 있는 배는 안전하지만, 그것이 배가 만들어진 목적은 아니다.",
    quote_en: "A ship in harbor is safe, but that is not what ships are built for.",
    author_ko: "존 A. 셰드",
    author_en: "John A. Shedd",
    author_title: "미국의 작가",
    category: "courage",
    category_ko: "용기와 희망",
    tags: ["항해", "도전", "모험"]
  },
  {
    id: 65,
    quote_ko: "용기는 압박 속에서도 우아함을 잃지 않는 것이다.",
    quote_en: "Courage is grace under pressure.",
    author_ko: "어니스트 헤밍웨이",
    author_en: "Ernest Hemingway",
    author_title: "노벨 문학상 수상 작가, 노인과 바다의 저자",
    category: "courage",
    category_ko: "용기와 희망",
    tags: ["우아함", "품격", "의연함"]
  },
  {
    id: 66,
    quote_ko: "태양을 향해 서라. 그러면 그림자는 언제나 등 뒤로 질 것이다.",
    quote_en: "Keep your face always toward the sunshine—and shadows will fall behind you.",
    author_ko: "월트 휘트먼",
    author_en: "Walt Whitman",
    author_title: "미국의 위대한 시인",
    category: "courage",
    category_ko: "용기와 희망",
    tags: ["햇살", "긍정", "빛"]
  },
  {
    id: 67,
    quote_ko: "당신이 할 수 있는 가장 큰 모험은 바로 당신이 꿈꾸는 삶을 살아가는 것이다.",
    quote_en: "The biggest adventure you can take is to live the life of your dreams.",
    author_ko: "오프라 윈프리",
    author_en: "Oprah Winfrey",
    author_title: "미국의 방송인이자 자선사업가",
    category: "courage",
    category_ko: "용기와 희망",
    tags: ["모험", "꿈", "자신감"]
  },
  {
    id: 68,
    quote_ko: "절대 포기하지 마라. 기적은 포기 직전에 일어난다.",
    quote_en: "Never give up. Miracles happen right before you quit.",
    author_ko: "작자 미상",
    author_en: "Anonymous",
    author_title: "세계적인 격언",
    category: "courage",
    category_ko: "용기와 희망",
    tags: ["불굴", "인내", "기적"]
  },
  {
    id: 69,
    quote_ko: "새로운 바다를 발견하려면 해안선이 시야에서 사라지는 것을 두려워하지 말아야 한다.",
    quote_en: "Man cannot discover new oceans unless he has the courage to lose sight of the shore.",
    author_ko: "앙드레 지드",
    author_en: "André Gide",
    author_title: "프랑스의 소설가이자 노벨 문학상 수상자",
    category: "courage",
    category_ko: "용기와 희망",
    tags: ["미지", "탐험", "항해"]
  },
  {
    id: 70,
    quote_ko: "우리가 날마다 마주하는 두려움과 맞서 싸울 때마다 우리는 힘과 용기와 자신감을 얻는다.",
    quote_en: "You gain strength, courage and confidence by every experience in which you really stop to look fear in the face.",
    author_ko: "엘리너 루스벨트",
    author_en: "Eleanor Roosevelt",
    author_title: "미국의 사회운동가",
    category: "courage",
    category_ko: "용기와 희망",
    tags: ["극복", "성장", "자신감"]
  },

  // 5. 사랑과 관계 (Love & Relationship)
  {
    id: 71,
    quote_ko: "사랑은 서로를 마주 보는 것이 아니라, 함께 같은 방향을 바라보는 것이다.",
    quote_en: "Love does not consist in gazing at each other, but in looking outward together in the same direction.",
    author_ko: "앙투안 드 생텍쥐페리",
    author_en: "Antoine de Saint-Exupéry",
    author_title: "프랑스의 작가, 어린 왕자의 저자",
    category: "love",
    category_ko: "사랑과 관계",
    tags: ["동행", "사랑", "방향"]
  },
  {
    id: 72,
    quote_ko: "가장 중요한 것은 눈에 보이지 않아. 마음으로 보아야만 분명하게 볼 수 있어.",
    quote_en: "It is only with the heart that one can see rightly; what is essential is invisible to the eye.",
    author_ko: "앙투안 드 생텍쥐페리 (어린 왕자 중)",
    author_en: "Antoine de Saint-Exupéry (The Little Prince)",
    author_title: "프랑스 작가",
    category: "love",
    category_ko: "사랑과 관계",
    tags: ["마음", "진심", "본질"]
  },
  {
    id: 73,
    quote_ko: "우리가 이 세상에서 할 수 있는 유일하게 위대한 일은 큰 사랑으로 작은 일을 행하는 것이다.",
    quote_en: "We cannot all do great things, but we can do small things with great love.",
    author_ko: "마더 테레사",
    author_en: "Mother Teresa",
    author_title: "노벨 평화상 수상자이자 성녀",
    category: "love",
    category_ko: "사랑과 관계",
    tags: ["헌신", "작은실천", "사랑"]
  },
  {
    id: 74,
    quote_ko: "사랑받고 싶다면 사랑하라, 그리고 사랑스럽게 행동하라.",
    quote_en: "If you would be loved, love, and be loveable.",
    author_ko: "벤저민 프랭클린",
    author_en: "Benjamin Franklin",
    author_title: "미국의 정치가이자 과학자",
    category: "love",
    category_ko: "사랑과 관계",
    tags: ["다정함", "사랑받는법", "관계"]
  },
  {
    id: 75,
    quote_ko: "친절한 말 한마디는 겨울 석 달을 따뜻하게 해 준다.",
    quote_en: "One kind word can warm three winter months.",
    author_ko: "동양 격언",
    author_en: "Eastern Proverb",
    author_title: "전통 격언",
    category: "love",
    category_ko: "사랑과 관계",
    tags: ["말한마디", "온기", "친절"]
  },
  {
    id: 76,
    quote_ko: "어둠으로 어둠을 몰아낼 수는 없다. 오직 빛만이 그렇게 할 수 있다. 증오로 증오를 몰아낼 수는 없다. 오직 사랑만이 그렇게 할 수 있다.",
    quote_en: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.",
    author_ko: "마틴 루터 킹 주니어",
    author_en: "Martin Luther King Jr.",
    author_title: "미국의 인권운동가",
    category: "love",
    category_ko: "사랑과 관계",
    tags: ["빛", "용서", "평화"]
  },
  {
    id: 77,
    quote_ko: "진정한 친구는 온 세상이 떠나갈 때 나를 찾아오는 사람이다.",
    quote_en: "A real friend is one who walks in when the rest of the world walks out.",
    author_ko: "월터 윈첼",
    author_en: "Walter Winchell",
    author_title: "미국의 저널리스트",
    category: "love",
    category_ko: "사랑과 관계",
    tags: ["우정", "진심", "친구"]
  },
  {
    id: 78,
    quote_ko: "사랑은 지배하는 것이 아니라 자유를 주는 것이다.",
    quote_en: "Love does not dominate; it cultivates.",
    author_ko: "에리히 프롬",
    author_en: "Erich Fromm",
    author_title: "독일의 심리학자이자 철학자, 사랑의 기술 저자",
    category: "love",
    category_ko: "사랑과 관계",
    tags: ["자유", "존중", "성숙"]
  },
  {
    id: 79,
    quote_ko: "사랑은 두 몸에 사는 하나의 영혼으로 이루어진다.",
    quote_en: "Love is composed of a single soul inhabiting two bodies.",
    author_ko: "아리스토텔레스",
    author_en: "Aristotle",
    author_title: "고대 그리스의 철학자",
    category: "love",
    category_ko: "사랑과 관계",
    tags: ["영혼", "일체", "순수"]
  },
  {
    id: 80,
    quote_ko: "남에게 대접을 받고자 하는 대로 너희도 남을 대접하라.",
    quote_en: "Do unto others as you would have them do unto you.",
    author_ko: "황금률 (성서 격언)",
    author_en: "The Golden Rule",
    author_title: "인류 보편의 도덕률",
    category: "love",
    category_ko: "사랑과 관계",
    tags: ["황금률", "배려", "역지사지"]
  },
  {
    id: 81,
    quote_ko: "용서는 나에게 상처 준 사람을 풀어주는 것이 아니라, 그 사람을 묶고 있던 내 마음의 사슬을 푸는 것이다.",
    quote_en: "Forgiveness liberates the soul. It removes fear.",
    author_ko: "넬슨 만델라",
    author_en: "Nelson Mandela",
    author_title: "남아프리카 공화국 대통령",
    category: "love",
    category_ko: "사랑과 관계",
    tags: ["용서", "해방", "자유"]
  },
  {
    id: 82,
    quote_ko: "친절함은 귀먹은 자도 들을 수 있고, 눈먼 자도 볼 수 있는 언어이다.",
    quote_en: "Kindness is a language which the deaf can hear and the blind can see.",
    author_ko: "마크 트웨인",
    author_en: "Mark Twain",
    author_title: "미국의 소설가",
    category: "love",
    category_ko: "사랑과 관계",
    tags: ["친절", "공감", "울림"]
  },
  {
    id: 83,
    quote_ko: "사랑의 반대말은 미움이 아니라 무관심이다.",
    quote_en: "The opposite of love is not hate, it's indifference.",
    author_ko: "엘리 위젤",
    author_en: "Elie Wiesel",
    author_title: "노벨 평화상 수상 작가",
    category: "love",
    category_ko: "사랑과 관계",
    tags: ["관심", "온정", "인간성"]
  },
  {
    id: 84,
    quote_ko: "가장 아름다운 꽃도 사랑 없이는 피어나지 못한다.",
    quote_en: "Even the most beautiful flower cannot blossom without love.",
    author_ko: "괴테",
    author_en: "Goethe",
    author_title: "독일의 대문호",
    category: "love",
    category_ko: "사랑과 관계",
    tags: ["개화", "보살핌", "사랑"]
  },
  {
    id: 85,
    quote_ko: "우리가 타인에게 베푼 온기는 언젠가 반드시 우리 자신에게 빛이 되어 돌아온다.",
    quote_en: "The warmth we give to others always returns as light to ourselves.",
    author_ko: "레프 톨스토이",
    author_en: "Leo Tolstoy",
    author_title: "러시아의 대문호이자 사상가",
    category: "love",
    category_ko: "사랑과 관계",
    tags: ["온기", "보답", "선행"]
  },

  // 6. 행복과 마음 (Happiness & Peace of Mind)
  {
    id: 86,
    quote_ko: "행복은 목적지가 아니라 여행하는 방식이다.",
    quote_en: "Happiness is not a destination, it is a way of travel.",
    author_ko: "마거릿 리 런벡",
    author_en: "Margaret Lee Runbeck",
    author_title: "미국의 소설가",
    category: "happiness",
    category_ko: "행복과 마음",
    tags: ["여정", "과정", "행복"]
  },
  {
    id: 87,
    quote_ko: "사람은 행복하기로 마음먹은 만큼 행복해진다.",
    quote_en: "Most folks are about as happy as they make up their minds to be.",
    author_ko: "에이브러햄 링컨",
    author_en: "Abraham Lincoln",
    author_title: "미국의 제16대 대통령",
    category: "happiness",
    category_ko: "행복과 마음",
    tags: ["마음먹기", "선택", "행복"]
  },
  {
    id: 88,
    quote_ko: "행복이란 당신이 생각하는 것, 당신이 말하는 것, 그리고 당신이 행하는 것이 조화를 이룰 때 찾아온다.",
    quote_en: "Happiness is when what you think, what you say, and what you do are in harmony.",
    author_ko: "마하트마 간디",
    author_en: "Mahatma Gandhi",
    author_title: "인도의 비폭력 독립운동 지도자",
    category: "happiness",
    category_ko: "행복과 마음",
    tags: ["조화", "일치", "평화"]
  },
  {
    id: 89,
    quote_ko: "자족할 줄 아는 사람이 진정한 부자이다.",
    quote_en: "He who is contented is rich.",
    author_ko: "노자",
    author_en: "Lao Tzu",
    author_title: "고대 중국의 철학자",
    category: "happiness",
    category_ko: "행복과 마음",
    tags: ["자족", "풍요", "감사"]
  },
  {
    id: 90,
    quote_ko: "행복의 문 하나가 닫히면 다른 문이 열린다. 하지만 우리는 닫힌 문만 너무 오래 쳐다보느라 열린 문을 보지 못한다.",
    quote_en: "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.",
    author_ko: "헬렌 켈러",
    author_en: "Helen Keller",
    author_title: "미국의 작가이자 교육가",
    category: "happiness",
    category_ko: "행복과 마음",
    tags: ["새로운문", "기회", "희망"]
  },
  {
    id: 91,
    quote_ko: "감사하는 마음은 모든 덕의 어머니일 뿐만 아니라 가장 위대한 덕이다.",
    quote_en: "Gratitude is not only the greatest of virtues, but the parent of all the others.",
    author_ko: "키케로",
    author_en: "Cicero",
    author_title: "로마의 철학자",
    category: "happiness",
    category_ko: "행복과 마음",
    tags: ["감사", "미덕", "평온"]
  },
  {
    id: 92,
    quote_ko: "마음의 평화는 당신이 통제할 수 없는 것들을 기꺼이 놓아줄 때 시작된다.",
    quote_en: "Peace comes from within. Do not seek it without.",
    author_ko: "붓다",
    author_en: "Buddha",
    author_title: "석가모니",
    category: "happiness",
    category_ko: "행복과 마음",
    tags: ["내면", "평화", "비움"]
  },
  {
    id: 93,
    quote_ko: "웃음이 없는 날은 가장 낭비된 날이다.",
    quote_en: "A day without laughter is a day wasted.",
    author_ko: "찰리 채플린",
    author_en: "Charlie Chaplin",
    author_title: "영국의 위대한 희극 영화 배우이자 감독",
    category: "happiness",
    category_ko: "행복과 마음",
    tags: ["웃음", "유머", "활력"]
  },
  {
    id: 94,
    quote_ko: "진정한 행복은 미래에 기대는 것이 아니라 현재를 온전히 누리는 것이다.",
    quote_en: "True happiness is to enjoy the present, without anxious dependence upon the future.",
    author_ko: "세네카",
    author_en: "Lucius Annaeus Seneca",
    author_title: "고대 로마의 스토아 철학자",
    category: "happiness",
    category_ko: "행복과 마음",
    tags: ["현재", "몰입", "평온"]
  },
  {
    id: 95,
    quote_ko: "바람이 나뭇가지를 흔들어도 뿌리 깊은 나무는 결코 흔들리지 않는다.",
    quote_en: "A tree with strong roots laughs at storms.",
    author_ko: "말레이 속담",
    author_en: "Malay Proverb",
    author_title: "전통 아시아 격언",
    category: "happiness",
    category_ko: "행복과 마음",
    tags: ["내면의힘", "중심", "흔들림없이"]
  },
  {
    id: 96,
    quote_ko: "작은 일에 기뻐할 줄 아는 사람이 가장 지혜롭고 행복하다.",
    quote_en: "Enjoy the little things, for one day you may look back and realize they were the big things.",
    author_ko: "로버트 브롤트",
    author_en: "Robert Brault",
    author_title: "미국의 작가이자 저널리스트",
    category: "happiness",
    category_ko: "행복과 마음",
    tags: ["소확행", "감사", "일상의기쁨"]
  },
  {
    id: 97,
    quote_ko: "꽃을 보고 미소 짓는 마음속에는 이미 평화가 깃들어 있다.",
    quote_en: "Peace is every step. It turns the endless path to joy.",
    author_ko: "틱낫한",
    author_en: "Thich Nhat Hanh",
    author_title: "베트남의 평화운동가이자 선승",
    category: "happiness",
    category_ko: "행복과 마음",
    tags: ["마음챙김", "평화", "미소"]
  },
  {
    id: 98,
    quote_ko: "남과 비교하지 마라. 어제의 당신보다 오늘의 당신이 더 나아졌다면 그것으로 충분하다.",
    quote_en: "There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self.",
    author_ko: "어니스트 헤밍웨이",
    author_en: "Ernest Hemingway",
    author_title: "미국의 소설가",
    category: "happiness",
    category_ko: "행복과 마음",
    tags: ["비교금지", "자기성장", "자존감"]
  },
  {
    id: 99,
    quote_ko: "마음속의 정원을 가꾸어라. 그러면 아름다운 나비는 저절로 날아올 것이다.",
    quote_en: "Build a garden in your mind, and butterflies will come naturally.",
    author_ko: "마리오 킨타나",
    author_en: "Mário Quintana",
    author_title: "브라질의 시인",
    category: "happiness",
    category_ko: "행복과 마음",
    tags: ["자기돌봄", "내면가꾸기", "자연스러움"]
  },
  {
    id: 100,
    quote_ko: "인생 최고의 행복은 사랑받고 있다는 확신이다.",
    quote_en: "The greatest happiness of life is the conviction that we are loved.",
    author_ko: "빅토르 위고",
    author_en: "Victor Hugo",
    author_title: "프랑스의 대문호, 레 미제라블의 저자",
    category: "happiness",
    category_ko: "행복과 마음",
    tags: ["사랑", "확신", "행복"]
  },
  {
    id: 101,
    quote_ko: "가장 어두운 밤도 언젠가는 끝나고 해는 다시 떠오를 것이다.",
    quote_en: "Even the darkest night will end and the sun will rise.",
    author_ko: "빅토르 위고",
    author_en: "Victor Hugo",
    author_title: "프랑스의 대문호",
    category: "courage",
    category_ko: "용기와 희망",
    tags: ["일출", "희망", "어둠의끝"]
  },
  {
    id: 102,
    quote_ko: "다른 사람의 삶을 사느라 당신의 시간을 낭비하지 마라.",
    quote_en: "Your time is limited, so don't waste it living someone else's life.",
    author_ko: "스티브 잡스",
    author_en: "Steve Jobs",
    author_title: "애플 창업자 (스탠퍼드 연설 중)",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["주체적삶", "시간", "자아실현"]
  },
  {
    id: 103,
    quote_ko: "당신이 평화롭기를 원한다면, 먼저 당신의 마음을 평화롭게 하라.",
    quote_en: "If you want peace, stop fighting. If you want peace of mind, stop fighting with your thoughts.",
    author_ko: "달라이 라마",
    author_en: "Dalai Lama",
    author_title: "티베트의 영적 지도자, 노벨 평화상 수상자",
    category: "happiness",
    category_ko: "행복과 마음",
    tags: ["평화", "마음의고요", "명상"]
  },
  {
    id: 104,
    quote_ko: "인내는 쓰지만 그 열매는 달다.",
    quote_en: "Patience is bitter, but its fruit is sweet.",
    author_ko: "장 자크 루소",
    author_en: "Jean-Jacques Rousseau",
    author_title: "프랑스의 철학자이자 사상가",
    category: "success",
    category_ko: "성공과 도전",
    tags: ["인내", "결실", "노력"]
  },
  {
    id: 105,
    quote_ko: "친절은 세상을 더 따뜻하게 만드는 유일한 화폐이다.",
    quote_en: "Kindness is the currency of a compassionate world.",
    author_ko: "랄프 왈도 에머슨",
    author_en: "Ralph Waldo Emerson",
    author_title: "미국의 사상가이자 시인",
    category: "love",
    category_ko: "사랑과 관계",
    tags: ["친절", "배려", "온기"]
  },
  {
    id: 106,
    quote_ko: "스스로를 신뢰하라. 그러면 어떻게 살아야 할지 알게 될 것이다.",
    quote_en: "Trust yourself, then you will know how to live.",
    author_ko: "괴테",
    author_en: "Goethe",
    author_title: "독일의 문호",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["자신감", "신뢰", "삶의지혜"]
  },
  {
    id: 107,
    quote_ko: "두려움은 항상 무지에서 태어난다.",
    quote_en: "Fear always springs from ignorance.",
    author_ko: "랄프 왈도 에머슨",
    author_en: "Ralph Waldo Emerson",
    author_title: "미국의 철학자",
    category: "wisdom",
    category_ko: "지혜와 배움",
    tags: ["지혜", "두려움", "극복"]
  },
  {
    id: 108,
    quote_ko: "어떤 일을 하기에 너무 늦은 나이란 없다.",
    quote_en: "It is never too late to be what you might have been.",
    author_ko: "조지 엘리엇",
    author_en: "George Eliot",
    author_title: "영국의 빅토리아 시대 작가",
    category: "success",
    category_ko: "성공과 도전",
    tags: ["도전", "새로운시작", "가능성"]
  },
  {
    id: 109,
    quote_ko: "오늘 하루를 그대의 마지막 날이라고 생각하라. 그러면 내일은 예상치 못한 축복이 될 것이다.",
    quote_en: "Think that every day has dawned on you as your last; sweet will be the hour that comes unhoped for.",
    author_ko: "호라티우스",
    author_en: "Horace",
    author_title: "고대 로마의 시인, 카르페 디엠의 주창자",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["카르페디엠", "순간의소중함", "현재"]
  },
  {
    id: 110,
    quote_ko: "진정한 기쁨은 마음이 맑고 고요할 때 스스로 솟아난다.",
    quote_en: "True joy rises quietly from a pure and tranquil heart.",
    author_ko: "채근담",
    author_en: "Caigentan (Treading the Root)",
    author_title: "명나라의 처세철학서",
    category: "happiness",
    category_ko: "행복과 마음",
    tags: ["기쁨", "맑음", "마음의평화"]
  },
  {
    id: 111,
    quote_ko: "말하기 전에 생각하고, 생각하기 전에 읽어라.",
    quote_en: "Think before you speak. Read before you think.",
    author_ko: "프랜 레보위츠",
    author_en: "Fran Lebowitz",
    author_title: "미국의 작가이자 사회비평가",
    category: "wisdom",
    category_ko: "지혜와 배움",
    tags: ["독서", "신중함", "언어"]
  },
  {
    id: 112,
    quote_ko: "내일의 짐까지 오늘 짊어지려 하지 마라. 하루의 괴로움은 그날로 족하다.",
    quote_en: "Do not borrow sorrow from tomorrow; each day has enough trouble of its own.",
    author_ko: "서양 지혜 격언",
    author_en: "Ancient Proverb",
    author_title: "생활의 지혜",
    category: "happiness",
    category_ko: "행복과 마음",
    tags: ["마음놓기", "걱정비우기", "오늘"]
  },
  {
    id: 113,
    quote_ko: "한 송이 들꽃에서도 온 우주의 아름다움을 볼 수 있어야 한다.",
    quote_en: "To see a World in a Grain of Sand, And a Heaven in a Wild Flower.",
    author_ko: "윌리엄 블레이크",
    author_en: "William Blake",
    author_title: "영국의 시인이자 화가",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["순수", "감탄", "우주"]
  },
  {
    id: 114,
    quote_ko: "우리가 서로에게 기대어 살 때 삶은 더욱 찬란해진다.",
    quote_en: "Life is all the more brilliant when we lean on each other and walk together.",
    author_ko: "헤르만 헤세",
    author_en: "Hermann Hesse",
    author_title: "독일의 작가, 노벨 문학상 수상자",
    category: "love",
    category_ko: "사랑과 관계",
    tags: ["연대", "동행", "온기"]
  },
  {
    id: 115,
    quote_ko: "그대의 온 마음을 다해 살아가라. 그것만이 그대가 이 세상에 남길 유일한 대답이다.",
    quote_en: "Live with your whole heart. That is the only answer you can leave for this world.",
    author_ko: "라이너 마리아 릴케",
    author_en: "Rainer Maria Rilke",
    author_title: "오스트리아의 서정 시인",
    category: "life",
    category_ko: "인생과 삶",
    tags: ["온마음", "진실함", "삶의답"]
  }
];

// 전역 객체 및 모듈 내보내기 지원 (Node/브라우저 양용)
if (typeof module !== 'undefined' && module.exports) {
  module.exports = QUOTES_DATA;
}
